// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJEk7xevyiMI2WxOI_nn4wUOmBdW0spo',
    appId: '1:928611418743:android:5050bbe50a521e3ab67c72',
    messagingSenderId: '928611418743',
    projectId: 'awesome-notes-76aa2',
    storageBucket: 'awesome-notes-76aa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnuxco0acHHj5S8vhFfPkyNZ1OZGOui-g',
    appId: '1:928611418743:ios:782bcdb56147d7ceb67c72',
    messagingSenderId: '928611418743',
    projectId: 'awesome-notes-76aa2',
    storageBucket: 'awesome-notes-76aa2.firebasestorage.app',
    iosBundleId: 'com.smsayedi.awesomeNotes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhAyF-j4EJxKtGFlBhOzGCsWGtG1fdhQ',
    appId: '1:928611418743:web:9aa63abbe15390bfb67c72',
    messagingSenderId: '928611418743',
    projectId: 'awesome-notes-76aa2',
    authDomain: 'awesome-notes-76aa2.firebaseapp.com',
    storageBucket: 'awesome-notes-76aa2.firebasestorage.app',
    measurementId: 'G-6HMKE720WX',
  );

}